version: '3.8'

services:
  questify:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./documents:/app/documents
      - ./config.json:/app/config.json
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
    restart: unless-stopped

  # Optional: Add a volume for persistent document storage
volumes:
  questify_documents:
    driver: local
